### ISSUE TITLE
Execute Akumina.SiteDeployer.exe from mac

### ISSUE THREAD

**Issue by ponmanin** [akumina/AkuminaTraining#1]
Dear Team,
i'm trying to build and deploy my application. I'm getting below error while deploy.

/bin/sh: /Users/m_490916/cslcode/EnterpriseSearchFrontEnd/CSL.ES/tools/Akumina.SiteDeployer.exe: cannot execute binary file
child_process.js:644
    throw err;

Any help will be appreciate...

developer machine is Mac.

**Comment by jasonarden** [comment]
Hi ponmanin,

Unfortunately the deployment tool is geared for Windows machines only at this moment, we have seen a few requests for mac support recently so we will be looking at other options to deploy without the SiteDeployer.exe (I love my macbook as well :)) .  For now parallels is recommended or another windows emulator for executing the deployment.  

As a short term solution, the npm run package command creates a zip file that you can import into App Manager as well.

-J
